server {
    listen 80;
    server_name localhost; # o la IP/hostname


    root /var/www/compras_comunitarias; # carpeta que contiene index.html
    index index.html;


    location / {
    try_files $uri $uri/ =404;
    }


    access_log /var/log/nginx/compras_comunitarias.access.log;
    error_log /var/log/nginx/compras_comunitarias.error.log;
}