server {
    listen 80;
    server_name localhost; # o la IP/hostname


    root /var/www/medios_audiovisuales; # carpeta que contiene index.html
    index index.html;


    location / {
    try_files $uri $uri/ =404;
    }


    access_log /var/log/nginx/medios_audiovisuales.access.log;
    error_log /var/log/nginx/medios_audiovisuales.error.log;
}